
DROP TABLE IF EXISTS USERS;
 
CREATE TABLE USERS (
  userid INT AUTO_INCREMENT  PRIMARY KEY,
  user_name VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS ORDERS;
 
CREATE TABLE ORDERS (
  orderid INT AUTO_INCREMENT  PRIMARY KEY,
  ordered_by VARCHAR(50) NOT NULL,
  order_product VARCHAR(50) NOT NULL,
  order_type VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS COMMENTS;
 
CREATE TABLE COMMENTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  commented_by VARCHAR(50) NOT NULL,
  order_id VARCHAR(50) NOT NULL,
  description VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS REPLIES;
 
CREATE TABLE REPLIES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  comment_id VARCHAR(50) NOT NULL,
  description VARCHAR(50) NOT NULL
);

